// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ctre/Phoenix.h"


#include "armSubsystem.h"
#include "../RobotMap.h"
#include "Robot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

armSubsystem::armSubsystem() : frc::Subsystem("armSubsystem") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    turretMotor = RobotMap::armSubsystemturretMotor;
    armMotor = RobotMap::armSubsystemarmMotor;
    armSolenoid = RobotMap::armSubsystemarmSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void armSubsystem::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void armSubsystem::Periodic() {
    // Put code here to be run every loop

}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void moveArmJoint(double speed){
	// * * MOVES THE ARM JOINT CURRENTLY A STATIC SPEED
	RobotMap::armSubsystemarmMotor->Set(speed*.01);
}

void moveTurret(double speed){
	// * * MOVE THE SWIVEL (TURRET) ARM
	RobotMap::armSubsystemturretMotor->Set(speed*.01);
}

void armExtend(bool ext){
	// * * EXTENDS THE ARM Set(bool on)
	RobotMap::armSubsystemarmSolenoid->Set(ext);
}
