// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/bendFixed.h"
#include "Commands/bendFree.h"
#include "Commands/extendArm.h"
#include "Commands/returnHome.h"
#include "Commands/rotate15.h"
#include "Commands/rotateFree.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystickController.reset(new frc::Joystick(0));
    
    extendArmButton.reset(new frc::JoystickButton(joystickController.get(), 1));
    extendArmButton->WhenPressed(new extendArm());
    returnHomeButton.reset(new frc::JoystickButton(joystickController.get(), 6));
    returnHomeButton->WhenPressed(new returnHome());
    bendFreeStick.reset(new frc::JoystickButton(joystickController.get(), 11));
    bendFreeStick->WhileHeld(new bendFree());
    bendFixedButton.reset(new frc::JoystickButton(joystickController.get(), 13));
    bendFixedButton->WhenPressed(new bendFixed());
    rotateFreeStick.reset(new frc::JoystickButton(joystickController.get(), 32));
    rotateFreeStick->WhileHeld(new rotateFree());
    rotate15Button.reset(new frc::JoystickButton(joystickController.get(), 17));
    rotate15Button->WhenPressed(new rotate15());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("extendArm", new extendArm());
    frc::SmartDashboard::PutData("returnHome", new returnHome());
    frc::SmartDashboard::PutData("bendFree", new bendFree());
    frc::SmartDashboard::PutData("bendFixed", new bendFixed());
    frc::SmartDashboard::PutData("rotateFree", new rotateFree());
    frc::SmartDashboard::PutData("rotate15", new rotate15());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getjoystickController() {
   return joystickController;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
