// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
	
	
	
	
	
	std::shared_ptr<frc::Joystick> joystickController;
	std::shared_ptr<frc::JoystickButton> extendArmButton;
	std::shared_ptr<frc::JoystickButton> returnHomeButton;
	std::shared_ptr<frc::JoystickButton> bendFreeStick;
	std::shared_ptr<frc::JoystickButton> bendFixedButton;
	std::shared_ptr<frc::JoystickButton> rotateFreeStick;
	std::shared_ptr<frc::JoystickButton> rotate15Button;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> getjoystickController();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
